services:
    node:
        container_name: node
        build:
            context: ./node
            dockerfile: Dockerfile
        image: node:latest
        ports:
            - 8080:8080
        environment:
            NODE_ENV: development
        volumes:
            - ./node/app:/usr/src/app

    mongodb:
        container_name: mongodb
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        image: mongodb:latest
        ports:
            - 8080:8080
        volumes:
            - ./mongodb/data:?
